-- 数据字典 / 系统参数（模块12 系统管理）
-- sys_dict 是全平台下拉选项的单一数据源：加一个状态值只需插一行，不用改表结构与页面代码。
-- 约定：dict_type 为字典分类，code 为数据库里实际存储的值，label 为界面展示文案。
--       user_role 是唯一 code 与 label 不一致的字典（库存 admin / user，界面显示中文）。
-- 幂等：CREATE TABLE IF NOT EXISTS + INSERT IGNORE（靠唯一键去重）。

CREATE TABLE IF NOT EXISTS `sys_dict` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dict_type`  VARCHAR(40)  NOT NULL                COMMENT '字典分类，如 achievement_type',
  `code`       VARCHAR(40)  NOT NULL                COMMENT '字典码，数据库实际存储值',
  `label`      VARCHAR(60)  NOT NULL                COMMENT '显示名',
  `sort_order` INT          NOT NULL DEFAULT 0      COMMENT '排序序号',
  `status`     VARCHAR(20)  NOT NULL DEFAULT '启用'  COMMENT '状态：启用 / 停用',
  `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_type_code` (`dict_type`, `code`),
  KEY `idx_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据字典表';

CREATE TABLE IF NOT EXISTS `sys_config` (
  `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `config_key`   VARCHAR(60)  NOT NULL                COMMENT '参数名，唯一',
  `config_value` VARCHAR(500) DEFAULT NULL            COMMENT '参数值',
  `remark`       VARCHAR(255) DEFAULT NULL            COMMENT '参数说明',
  `updated_at`   DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数表';

INSERT IGNORE INTO `sys_dict` (`dict_type`, `code`, `label`, `sort_order`) VALUES
('user_role', 'admin', '管理员', 1),
('user_role', 'user', '普通用户', 2),
('user_status', '启用', '启用', 1),
('user_status', '禁用', '禁用', 2),
('member_type', '导师', '导师', 1),
('member_type', '博士', '博士研究生', 2),
('member_type', '硕士', '硕士研究生', 3),
('member_type', '本科', '本科生', 4),
('member_type', '访客', '访客', 5),
('member_status', '在组', '在组', 1),
('member_status', '已离组', '已离组', 2),
('member_status', '已毕业', '已毕业', 3),
('member_status', '暂停', '暂停', 4),
('workstation_status', '空闲', '空闲', 1),
('workstation_status', '使用中', '使用中', 2),
('workstation_status', '维修中', '维修中', 3),
('apply_type', '入组', '入组申请', 1),
('apply_type', '离组', '离组申请', 2),
('apply_type', '毕业', '毕业申请', 3),
('approval_status', '待审批', '待审批', 1),
('approval_status', '已通过', '已通过', 2),
('approval_status', '已驳回', '已驳回', 3),
('approval_status', '已撤销', '已撤销', 4),
('approval_biz_type', '入组', '入组申请', 1),
('approval_biz_type', '离组', '离组申请', 2),
('approval_biz_type', '请假', '请假申请', 3),
('approval_biz_type', '设备借用', '设备借用', 4),
('approval_biz_type', '报销', '经费报销', 5),
('approval_biz_type', '成果', '成果登记', 6),
('project_type', '纵向', '纵向项目', 1),
('project_type', '横向', '横向项目', 2),
('project_type', '校级', '校级项目', 3),
('project_type', '企业合作', '企业合作项目', 4),
('project_stage', '申报', '申报', 1),
('project_stage', '立项', '立项', 2),
('project_stage', '进行中', '进行中', 3),
('project_stage', '结题', '结题', 4),
('project_stage', '归档', '归档', 5),
('milestone_status', '未完成', '未完成', 1),
('milestone_status', '已完成', '已完成', 2),
('milestone_status', '已延期', '已延期', 3),
('task_priority', '高', '高', 1),
('task_priority', '中', '中', 2),
('task_priority', '低', '低', 3),
('task_status', '待办', '待办', 1),
('task_status', '进行中', '进行中', 2),
('task_status', '待审核', '待审核', 3),
('task_status', '已完成', '已完成', 4),
('activity_type', '例行组会', '例行组会', 1),
('activity_type', '文献分享', '文献分享', 2),
('activity_type', '开题', '开题报告', 3),
('activity_type', '中期', '中期检查', 4),
('activity_type', '预答辩', '预答辩', 5),
('activity_type', '学术讲座', '学术讲座', 6),
('activity_type', '竞赛', '学科竞赛', 7),
('activity_type', '团建', '团建活动', 8),
('activity_type', '外出调研', '外出调研', 9),
('activity_status', '待进行', '待进行', 1),
('activity_status', '进行中', '进行中', 2),
('activity_status', '已结束', '已结束', 3),
('activity_status', '已取消', '已取消', 4),
('sign_status', '已签到', '已签到', 1),
('sign_status', '请假', '已请假', 2),
('sign_status', '迟到', '迟到', 3),
('sign_status', '缺席', '缺席', 4),
('achievement_type', '论文', '论文', 1),
('achievement_type', '专利', '专利', 2),
('achievement_type', '软著', '软件著作权', 3),
('achievement_type', '标准', '标准', 4),
('achievement_type', '获奖', '获奖', 5),
('achievement_type', '竞赛', '竞赛', 6),
('achievement_level', 'SCI', 'SCI', 1),
('achievement_level', 'EI', 'EI', 2),
('achievement_level', '核心', '中文核心', 3),
('achievement_level', '发明', '发明专利', 4),
('achievement_level', '实用新型', '实用新型', 5),
('achievement_level', '外观', '外观设计', 6),
('achievement_status', '投稿', '投稿', 1),
('achievement_status', '在审', '在审', 2),
('achievement_status', '录用', '录用', 3),
('achievement_status', '发表', '已发表', 4),
('achievement_status', '检索', '已检索', 5),
('device_status', '正常', '正常', 1),
('device_status', '借用中', '借用中', 2),
('device_status', '维修中', '维修中', 3),
('device_status', '报废', '已报废', 4),
('borrow_status', '待审批', '待审批', 1),
('borrow_status', '已批准', '已批准', 2),
('borrow_status', '已借出', '已借出', 3),
('borrow_status', '已归还', '已归还', 4),
('borrow_status', '已驳回', '已驳回', 5),
('borrow_status', '已超期', '已超期', 6),
('repair_status', '待处理', '待处理', 1),
('repair_status', '维修中', '维修中', 2),
('repair_status', '已完成', '已完成', 3),
('repair_status', '转报废', '转报废', 4),
('reserve_status', '已预约', '已预约', 1),
('reserve_status', '已使用', '已使用', 2),
('reserve_status', '已取消', '已取消', 3),
('consumable_record_type', '领用', '领用', 1),
('consumable_record_type', '补充', '补充入库', 2),
('attendance_status', '正常', '正常', 1),
('attendance_status', '迟到', '迟到', 2),
('attendance_status', '早退', '早退', 3),
('attendance_status', '缺勤', '缺勤', 4),
('attendance_status', '请假', '请假', 5),
('attendance_status', '补签', '补签', 6),
('attendance_sign_type', '正常', '正常签到', 1),
('attendance_sign_type', '手动补签', '手动补签', 2),
('attendance_sign_type', '定位签到', '定位签到', 3),
('attendance_sign_type', '扫码签到', '扫码签到', 4),
('duty_shift', '上午', '上午', 1),
('duty_shift', '下午', '下午', 2),
('duty_shift', '全天', '全天', 3),
('duty_type', '常规', '常规值班', 1),
('duty_type', '节假日', '节假日值班', 2),
('leave_type', '事假', '事假', 1),
('leave_type', '病假', '病假', 2),
('leave_type', '外出', '外出', 3),
('leave_type', '出差', '出差', 4),
('leave_status', '待审批', '待审批', 1),
('leave_status', '已通过', '已通过', 2),
('leave_status', '已驳回', '已驳回', 3),
('leave_status', '已销假', '已销假', 4),
('leave_status', '已撤销', '已撤销', 5),
('expense_category', '设备', '设备费', 1),
('expense_category', '材料', '材料费', 2),
('expense_category', '差旅', '差旅费', 3),
('expense_category', '会议', '会议费', 4),
('expense_category', '版面费', '版面费', 5),
('expense_category', '其他', '其他', 6),
('expense_status', '待审批', '待审批', 1),
('expense_status', '已通过', '已通过', 2),
('expense_status', '已驳回', '已驳回', 3),
('expense_status', '已入账', '已入账', 4),
('expense_status', '已撤销', '已撤销', 5),
('expense_record_type', '收入', '收入', 1),
('expense_record_type', '支出', '支出', 2),
('notice_type', '公告', '公告', 1),
('notice_type', '系统通知', '系统通知', 2),
('notice_type', '审批提醒', '审批提醒', 3),
('notice_type', '截止提醒', '截止提醒', 4),
('notice_type', '组会提醒', '组会提醒', 5),
('notice_scope', '全体', '全体成员', 1),
('notice_scope', '指定成员', '指定成员', 2),
('message_type', '系统通知', '系统通知', 1),
('message_type', '审批提醒', '审批提醒', 2),
('message_type', '截止提醒', '截止提醒', 3),
('message_type', '组会提醒', '组会提醒', 4),
('report_period', '周报', '周报', 1),
('report_period', '月报', '月报', 2);

INSERT IGNORE INTO `sys_config` (`config_key`, `config_value`, `remark`) VALUES
('work_start_time', '09:00', '考勤上班时间基准，用于迟到判定'),
('work_end_time', '18:00', '考勤下班时间基准，用于早退判定'),
('late_grace_minutes', '15', '迟到判定的宽限分钟数'),
('attendance_required_hours', '8', '每日标准工时，用于工时统计'),
('session_hours', '24', '登录会话有效期，单位小时'),
('borrow_overdue_days', '1', '设备借用超过计划归还日多少天标记为已超期'),
('developing_tip_enabled', '启用', '未开放功能是否提示正在开发中：启用 / 停用');
